### ISSUE TITLE
Why do I need to load 2D data when training 3D data？

### ISSUE THREAD

**Issue by APeiZou** [SangbumChoi/MobileHumanPose#2]
![image](https://user-images.githubusercontent.com/49524647/123750955-bde7d980-d8e9-11eb-95c2-00b69fc41a3d.png)
Why do I need to load 2D MPII dataset when training the 3D Human36M  dataset？

**Comment by SangbumChoi** [comment]
@APeiZou Theoritically you don't need to add 2D dataset while training 3D dataset. However, it is widely known that additional 2D dataset without z axis is giving more robustness to the 3D human pose estimation model due to seeing diverse dataset. You can see more detail at maybe https://arxiv.org/abs/1711.08229 (hope i linked appropriate paper).
